config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :plans do
    resources :features
  end
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feature.rb
class Feature < ApplicationRecord
  belongs_to :plan
end

app/models/plan.rb
class Plan < ApplicationRecord
    has_many :features
    validates :plan_name, presence: true,
                    length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
    def create
    @plan = Plan.find(params[:plan_id])
    @features = @plan.features.create(feature_params)
    redirect_to plan_path(@plan)
  end
 
  private
    def feature_params
      params.require(:feature).permit(:name, :code, :unit_price, :max_unit_limit)
    end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
    def index
        @plan = Plan.all
    end

    def show
        @plan = Plan.find(params[:id])
    end
    def new
    end

    def create
        @plan = Plan.new(plan_params)
        if @plan.save
            redirect_to @plan
        else
            render 'new'
        end
    end

    def destroy
        @plan = Plan.find(params[:id])
        @plan.destroy
        redirect_to plans_path
    end

    private
    def plan_params
        params.require(:plan).permit(:plan_name, :monthly_fee)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PaymentSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/index.html.erb
<h1>Available Plans</h1>
 <%= link_to 'Create New Plan', new_plan_path %>
<table> 
<tr>
    <th>Plan Name</th>
    <th>Monthly Fee</th>
    <th colspan="2"></th>
</tr>
<% @plan.each do |plan| %> <tr>
<td><%= plan.plan_name %></td>
<td><%= plan.monthly_fee %></td>
<td><%= link_to 'Show', plan_path(plan) %></td>
    <td><%= link_to 'Destroy', plan_path(plan),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/plans/new.html.erb
 <h1>Create Plan</h1>

 <%= form_with scope: :plan, url: plans_path, local: true do |form| %>
<p>
<%= form.label :plan_name %><br>
<%= form.text_field :plan_name %> </p>
<p>
<%= form.label :monthly_fee %><br> 
<%= form.text_area :monthly_fee %>
</p>
  <p>
    <%= form.submit %>
</p>
<% end %>

app/views/plans/show.html.erb
 <p> <strong>Plan Name:</strong> <%= @plan.plan_name %>
</p>
<p> <strong>Monthly Fee:</strong> <%= @plan.monthly_fee %>
</p>

<h2>Features</h2>
<% @plan.features.each do |feature| %>
  <p>
    <strong>Name:</strong>
    <%= feature.name %>
  </p>
 
  <p>
    <strong>Code:</strong>
    <%= feature.code %>
  </p>

   <p>
    <strong>unit_price:</strong>
    <%= feature.unit_price %>
  </p>

   <p>
    <strong>max_unit_limit:</strong>
    <%= feature.max_unit_limit %>
  </p>


<% end %>

<h2>Add Feature:</h2>
<%= form_with(model: [ @plan, @plan.features.build ], local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :code %><br>
    <%= form.text_area :code %>
  </p>

   <p>
    <%= form.label :unit_price %><br>
    <%= form.text_area :unit_price %>
  </p>

   <p>
    <%= form.label :max_unit_limit %><br>
    <%= form.text_area :max_unit_limit %>
  </p>


  <p>
    <%= form.submit %>
  </p>
<% end %>


<%= link_to 'Back', plans_path %>

app/views/welcome/index.html.erb
<style>



section{
}
.background {
    background-image: url(bg.jpg);
}
.container {

  width: 50%;
  border: 2px solid black;
  padding: 10px;
  text-align: center;

    position: absolute;
    left: 35%;
    top: 35%;
    height: 150px;
    width: 300px;

}

h1 {
  background-color: black;
  color: white;
  font-family: serif;
  text-align: center
}
a:link, a:visited {
  background-color: black;
  color: white;
  padding: 10px 20px;
  text-align: center;
  display: inline-block;
}

a:hover, a:active {
   align: center;
  background-color: gray;
}


</style>


<h1>Welcome to Payment System</h1>

<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <p>
  <%= link_to "Sign up", new_user_registration_path %>  |
  <%= link_to "Login", new_user_session_path %> 
  </p>

<% end %>

<%= link_to 'Plans', controller: 'plans' %>